// <auto-generated />
using System;
using GoldRateApi.CommonClasses;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace GoldRateApi.Migrations
{
    [DbContext(typeof(DbGoldRateContext))]
    [Migration("20200706191149_DbGoldRateContextMigration")]
    partial class DbGoldRateContextMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("GoldRateApi.Models.mGoldRate", b =>
                {
                    b.Property<int>("iID")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("iID")
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("GoldCarat")
                        .HasColumnName("cGoldCarat")
                        .HasColumnType("Varchar(20)");

                    b.Property<decimal>("GoldPriceAfternoon")
                        .HasColumnName("rGoldPriceAfternoon")
                        .HasColumnType("numeric(9,3)");

                    b.Property<decimal>("GoldPriceEvening")
                        .HasColumnName("rGoldPriceEvening")
                        .HasColumnType("numeric(9,3)");

                    b.Property<decimal>("GoldPriceMorning")
                        .HasColumnName("rGoldPriceMorning")
                        .HasColumnType("numeric(9,3)");

                    b.Property<decimal>("GoldPriceYesterday")
                        .HasColumnName("rGoldPriceYesterday")
                        .HasColumnType("numeric(9,3)");

                    b.Property<DateTime?>("UpdatedDateTime")
                        .HasColumnName("dUpdatedDateTime")
                        .HasColumnType("datetime");

                    b.HasKey("iID");

                    b.ToTable("T_UaeGoldRate");
                });
#pragma warning restore 612, 618
        }
    }
}
